#ifndef _G12COMMONEXPORT_H_
#define _G12COMMONEXPORT_H_
#include "dllexport.h"
#ifdef  G12COMMON_RESOURCE_LIBRARY
#  define RESOURCE_LIBRARY_EXPORT  Q_DECL_EXPORT
#else
#  define RESOURCE_LIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif _G12COMMONEXPORT_H_

