#ifndef    _VISION_CAMERAMANAGER_ERROR_H_
#define    _VISION_CAMERAMANAGER_ERROR_H_

enum Em_Error_CameraManager
{
    VISION_CAMERAMANAGER = 4300,
    VISION_CAMERAMANAGER_EXECUTE_CAMID_ERROR,
    VISION_CAMERAMANAGER_EXECUTE_CREATECAMERA_ERROR,
};

#endif